# Generated by Django 5.1.1 on 2024-12-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorProductos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='creador',
            new_name='user_id',
        ),
    ]
